apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: junior-tracker-ingress
  namespace: junior-tracker
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - tracker.golovanov.me
      secretName: junior-tracker-tls
  rules:
    - host: tracker.golovanov.me
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: junior-tracker-api
                port:
                  number: 80
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: junior-tracker-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: junior-tracker-frontend
                port:
                  number: 80
